# Generated by Django 3.0.8 on 2020-09-21 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infoApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='updates',
            name='imageLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='updates',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
