# Generated by Django 3.0.8 on 2020-09-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoApi', '0002_auto_20200921_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
