# Generated by Django 3.0.8 on 2020-09-15 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='message',
        ),
    ]
