# Generated by Django 3.0.8 on 2020-09-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApi', '0004_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
